version: "3.8"

services:
  postgres:
    image: postgres:10.12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-bank-server:
    image: spring-bank/spring-bank-server:latest
    depends_on:
      - postgres
    ports:
      - 80:80
    environment:
      - DB_URL=postgresql://postgres:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin

volumes:
  postgres-data:
